/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/BatchExpenses': RouteRecordInfo<'/BatchExpenses', '/BatchExpenses', Record<never, never>, Record<never, never>>,
    '/Categories': RouteRecordInfo<'/Categories', '/Categories', Record<never, never>, Record<never, never>>,
    '/ExpenseDashboard': RouteRecordInfo<'/ExpenseDashboard', '/ExpenseDashboard', Record<never, never>, Record<never, never>>,
    '/Expenses': RouteRecordInfo<'/Expenses', '/Expenses', Record<never, never>, Record<never, never>>,
    '/IncomeDashboard': RouteRecordInfo<'/IncomeDashboard', '/IncomeDashboard', Record<never, never>, Record<never, never>>,
    '/Incomes': RouteRecordInfo<'/Incomes', '/Incomes', Record<never, never>, Record<never, never>>,
    '/Meters': RouteRecordInfo<'/Meters', '/Meters', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/BatchExpenses.vue': {
      routes: '/BatchExpenses'
      views: never
    }
    'src/pages/Categories.vue': {
      routes: '/Categories'
      views: never
    }
    'src/pages/ExpenseDashboard.vue': {
      routes: '/ExpenseDashboard'
      views: never
    }
    'src/pages/Expenses.vue': {
      routes: '/Expenses'
      views: never
    }
    'src/pages/IncomeDashboard.vue': {
      routes: '/IncomeDashboard'
      views: never
    }
    'src/pages/Incomes.vue': {
      routes: '/Incomes'
      views: never
    }
    'src/pages/Meters.vue': {
      routes: '/Meters'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
